Install python38-wheel package
ansible/python-builder-image pull request #17
Opened 2020-12-17 15:44 UTC by pabelanger

This moves away from python36 to python38 wheels.

Depends-On: https://github.com/ansible/python-base-image/pull/7
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

2020-12-17 17:45 UTC, pabelanger commented
Pull-request updated, HEAD is now f5370477893096d1782da87e52ae6faac9c621fc

2020-12-17 18:14 UTC, pabelanger commented
recheck

2020-12-17 18:15 UTC, pabelanger commented
recheck

2020-12-17 19:16 UTC, pabelanger commented
recheck

2020-12-17 19:31 UTC, AlanCoding approved these changes

2020-12-17 19:32 UTC, jladdjr approved these changes

2020-12-17 19:37 UTC, shanemcd requested changes
I would like to hold off on this until we have answers for: https://github.com/ansible/ansible-runner/pull/594#issuecomment-747647955

2020-12-18 15:25 UTC, shanemcd approved these changes
After discussion yesterday we have decided to #shipit.

2020-12-18 15:58 UTC, merged